language: node_js
node_js:
- '8'
before_install:
- openssl aes-256-cbc -K $encrypted_6c011acebbb9_key -iv $encrypted_6c011acebbb9_iv
  -in google-auth-token.txt.enc -out google-auth-token.txt -d
install:
- npm install -g firebase-tools
- cd functions/
- npm install
- cd ..
# - firebase functions:delete generateBookingIds --force
# - firebase functions:delete generateUtteranceIndexes --force
script:
- echo "Deploy!"
after_success:
- firebase deploy --project tgd-experiment --token $FIREBASE_TOKEN
